apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
        - name: library
          image: josehr/library
          env:
            - name: MONGO_URI
              value: mongodb://library-mongo-srv:27017/library

---
apiVersion: v1
kind: Service
metadata:
  name: library-srv
spec:
  selector:
    app: library
  ports:
    - name: library
      protocol: TCP
      port: 3001
      targetPort: 3001
