apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-mongo
  template:
    metadata:
      labels:
        app: library-mongo
    spec:
      containers:
        - name: library-mongo
          image: mongo
---

apiVersion: v1
kind: Service
metadata:
  name: library-mongo-srv
spec:
  selector:
    app: library-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
